# Generated by Django 6.0.6 on 2026-07-06 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('frequency', models.CharField(max_length=100)),
                ('disease', models.CharField(choices=[('BP', 'Blood Pressure'), ('DIABETES', 'Diabetes'), ('THYROID', 'Thyroid'), ('HEART', 'Heart'), ('VITAMINS', 'Vitamins'), ('ANTIBIOTICS', 'Antibiotics'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
