# Generated by Django 6.0.7 on 2026-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='quantity_per_dose',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicine',
            name='daily_frequency',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity_per_dose',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
