# Generated by Django 6.0.7 on 2026-07-26 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_medicationschedule_quantity_per_dose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('disease', models.CharField(default='OTHER', max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('remaining_quantity', models.IntegerField(default=0)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('action', models.CharField(default='ADDED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
