# Generated by Django 6.0.7 on 2026-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_caregiverassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.CharField(max_length=100),
        ),
    ]
