# Generated by Django 6.0.7 on 2026-08-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medicine_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
