# Generated by Django 6.0.7 on 2026-08-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_notifications_user_medicine_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medicine_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
